Home page added
DmitryGn/flutter_ecommerce_app pull request #4
Opened 2023-10-05 19:26 UTC by DmitryGn

2023-10-07 16:08 UTC, VadymPinchuk requested changes

2023-10-07 16:08 UTC, VadymPinchuk commented on pubspec.lock
> +  args:
не стосується даного домашнього завдання

2023-10-08 09:23 UTC, DmitryGn commented on assets/icons/add_wishlist.svg
Так, я розумію, але хотів би використовувати іконки з можливістю змінювати їх дизайн.

2023-10-08 15:29 UTC, VadymPinchuk approved these changes

2023-10-10 17:37 UTC, closed without merging